name: Databricks CI on Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  run-databricks-job:
    runs-on: ubuntu-latest
    steps:
      # This is the first step from the successful test file
      - name: Checkout repository
        uses: actions/checkout@v3

      # This is the rebuilt Databricks step
      - name: Run Databricks Job
        uses: databricks/run-job@main
        with:
          databricks-host: "https://dbc-72efe024-1189.cloud.databricks.com"
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
          job-id: "1475150698443343"
          git-commit: ${{ github.sha }}